### PR TITLE
Octavia: add new policies for the Amphora VM

### PR DESCRIPTION
**Pull request by gthiemonge**
Resolves: rhbz#2073491

### CODE REVIEW

**Review by jpichon — COMMENTED** [review]
This looks reasonable to me, thank you for the patch and including the tests!

My only concern would be that the tests only include enforcing logs. Is the patch confirmed to work on a real system? With enforcing, SELinux stops at the first denial, while permissive keeps going and would show if there are other denials hidden behind these ones.

**Comment by gthiemonge** [comment]
> This looks reasonable to me, thank you for the patch and including the tests!
> 
> My only concern would be that the tests only include enforcing logs. Is the patch confirmed to work on a real system? With enforcing, SELinux stops at the first denial, while permissive keeps going and would show if there are other denials hidden behind these ones.

Yes it works on a real system, I updated the Octavia amphora image many times and I ran most of the octavia-tempest-plugin tests (basically I choosed the tests that trigger those behaviors in the amphora), I iterated a few times before the tests passed.

**Comment by cjeanner** [comment]
So basically, this allows haproxy_t to exec shell script. It raises some security concerns imho, we should get some other advice on that. And maybe find a better way to make the octavia thing work without the need of this kind of policy.

**Comment by jpichon** [comment]
We could also add it behind a disabled-by-default boolean that only Octavia enabled in THT, to limit the impact.

**Comment by cjeanner** [comment]
That would already be better. IMHO we should understand why those rights are needed, and modify the way the service is working to avoid them.
Octavia exposes an haproxy to the public, we certainly don't want it to exec shell things for any reason....

**Comment by cjeanner** [comment]
I think this one is the proper fix to the issue: https://review.opendev.org/c/openstack/octavia/+/837721

IMHO, we should revert this policy modification asap.

**Comment by jpichon** [comment]
Ack! Does this need a full revert, or just the shell_exect_t rule?

**Comment by cjeanner** [comment]
a full revert as a first step. If really, I'll work with @gthiemonge on a clean solution. Though I really hope we won't have to touch SELinux anymore for that reload ;).

**Pull request merged**
