### PR TITLE
Cinder in WSGI needs to create dir in statedir

### PR DESCRIPTION
**Pull request by tobias-urdin**
See https://review.rdoproject.org/r/#/c/26194/ for details.

### CODE REVIEW

**Comment by jpichon** [comment]
Thank you for the patch! The addition looks fine to me, although I'm not sure why we didn't hit this before.

Were you able to test with this new rule? Can you confirm that it's the only addition needed to get past the problem? (In Enforcing mode it's not uncommon for further denials to be hidden beyond the first one.)

If possible, would you be able to provide a copy of the denial from /var/log/audit/audit.log as well? Whenever possible we try to keep a copy of those under /tests/ to avoid regressions. I can add it in a separate patch if you prefer but I couldn't find it in the linked review either. Thank you!

**Comment by tobias-urdin** [comment]
type=AVC msg=audit(1585843108.853:7813309): avc:  denied  { write } for  pid=3306875 comm="httpd" name="cinder" dev="dm-0" ino=1230986 scontext=system_u:system_r:httpd_t:s0 tcontext=system_u:object_r:cinder_var_lib_t:s0 tclass=dir

**Comment by tobias-urdin** [comment]
I'm testing, I'll let you know with the result :)

**Comment by tobias-urdin** [comment]
cinder-test.te
```
module cinder-test 1.0;

require {
  type httpd_t;
  type cinder_var_lib_t;
  class dir { add_name write create };
}

#============= httpd_t ==============
allow httpd_t cinder_var_lib_t:dir { add_name write create };
```

```
checkmodule -M -m -o cinder-test.mod cinder-test.te
semodule_package -o cinder-test.pp -m cinder-test.mod
semodule -i cinder-test.pp
```

This makes it work, I'll update the PR.
Thanks for your help, learned something new :)

**Comment by tobias-urdin** [comment]
All three denies:

type=AVC msg=audit(1585843550.178:7813550): avc:  denied  { add_name } for  pid=3306876 comm="httpd" name="groups" scontext=system_u:system_r:httpd_t:s0 tcontext=system_u:object_r:cinder_var_lib_t:s0 tclass=dir

type=AVC msg=audit(1585843799.707:7814032): avc:  denied  { write } for  pid=3306876 comm="httpd" name="cinder" dev="dm-0" ino=1230986 scontext=system_u:system_r:httpd_t:s0 tcontext=system_u:object_r:cinder_var_lib_t:s0 tclass=dir

type=AVC msg=audit(1585843767.395:7814013): avc:  denied  { create } for  pid=3306875 comm="httpd" name="groups" scontext=system_u:system_r:httpd_t:s0 tcontext=system_u:object_r:cinder_var_lib_t:s0 tclass=dir

**Comment by jpichon** [comment]
Awesome, thank you for the update! Yes, SELinux in Enforcing mode stops at the first problem then moves on. That's why we usually ask people to reproduce the issue in Permissive mode first so we get all the denials, rather than play whack-a-mole with patches!! I'll merge this, open an RDO SELinux bug and use that to add the tests. Cheers

**Comment by jpichon** [comment]
Just for reference:
https://github.com/redhat-openstack/openstack-selinux/commit/386b42
https://bugzilla.redhat.com/show_bug.cgi?id=1820504

**Pull request merged**
