### PR TITLE
Octavia: RHEL8 Amphora policy additions

### PR DESCRIPTION
**Pull request by nmagnezi**
- Octavia Policies
- Tests based on audit2why

Resolves: rhbz#1684885

### CODE REVIEW

**Comment by nmagnezi** [comment]
Ran tests locally on an RHEL8 machine: [here](https://gist.github.com/nmagnezi/39b33d755165eedc280e111dbe42e964#file-gistfile1-txt
)


The ERROR msgs on [lines 284-285](https://gist.github.com/nmagnezi/39b33d755165eedc280e111dbe42e964#file-gistfile1-txt-L284-L287) are not related to this PR and I'll file a separate Bugzilla for handling those.

**Comment by jpichon** [comment]
I will try to run the tests on a RHEL8 machine to reproduce the error mentioned. Meanwhile, it looks like 3 AVCs remain:
```
bz1684885:5:type=AVC msg=audit(1551867084.102:44): avc:  denied  { read } for  pid=1376 comm="ip" dev="nsfs" ino=4026532223 scontext=system_u:system_r:haproxy_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=file permissive=1
bz1684885:6:type=AVC msg=audit(1551867084.102:44): avc:  denied  { open } for  pid=1376 comm="ip" path="/run/netns/amphora-haproxy" dev="nsfs" ino=4026532223 scontext=system_u:system_r:haproxy_t:s0 tcontext=system_u:system_r:unconfined_service_t:s0 tclass=file permissive=1
bz1684885:8:type=AVC msg=audit(1551867108.032:46): avc:  denied  { execute } for  pid=1431 comm="kill" path="/usr/bin/kill" dev="vda1" ino=538254 scontext=system_u:system_r:haproxy_t:s0 tcontext=system_u:object_r:bin_t:s0 tclass=file permissive=1
Results: 770 total, 3 failed
```

It looks like the `domain_can_mmap_files` boolean only covers "allow haproxy_t bin_t:file map;" from the original bug and we need 2 more rules for this to work:
```
allow haproxy_t bin_t:file execute;
allow haproxy_t unconfined_service_t:file { open read };
```
I'm a bit suspicious about the `unconfined_service_t` bit though... @lhh what do you think?

**Comment by nmagnezi** [comment]
Hey Julie,

As you proposed, I added both rules, see [here](https://github.com/redhat-openstack/openstack-selinux/commit/0f46cf99c3b44f8e58918ed23185a43c50aa7501).
Additionally, [per your suggestion on rhbz#1686004](https://bugzilla.redhat.com/show_bug.cgi?id=1686004#c4), I deployed container-selinux and ran the tests. Results look much better now (I'm ignoring duplicate definition for now).

The results:

- [Without container-selinux](https://gist.github.com/nmagnezi/bf9620593462cd64a25c5ff7f1a34ccb)
- [With container-selinux](https://gist.github.com/nmagnezi/2709b93ad7aca1856b6b84933dd5c426)

**Comment by lhh** [comment]
So...
[root@localhost openstack-selinux]# ip netns add tmp
[root@localhost openstack-selinux]# ls -lZ /run/netns/tmp
-r--r--r--. 1 root root unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 0 Mar 11 10:07 /run/netns/tmp
[root@localhost openstack-selinux]# restorecon !$
restorecon /run/netns/tmp
restorecon: Could not set context for /run/netns/tmp:  Operation not permitted

**Comment by lhh** [comment]
It looks like netns doesn't have a way to set file labels - either at creation time or after. So, this is fine for now.

**Comment by lhh** [comment]
Furthermore, these files should be ifconfig_var_run_t, given selinux inheritance rules:

drwxr-xr-x. 2 root root unconfined_u:object_r:ifconfig_var_run_t:s0 60 Mar 11 10:07 /run/netns/

**Comment by lhh** [comment]
As of this writing, here is the latest commit for nsfs (namespace filesystem):

https://github.com/torvalds/linux/blob/24dce0800baaa508b1a8ccf01ae0a9c8e600a5aa/fs/nsfs.c

I don't see a way to set xattrs, so I think this is the best we can do for now?

**Comment by lhh** [comment]
This seems to be a difference between RHEL7 vs F28 (I didn't check before that) and RHEL8.

**Comment by lhh** [comment]
[root@shale ~]# ip netns add tmp
[root@shale ~]# ls -lZ /run/netns/tmp
-r--r--r--. root root system_u:object_r:proc_t:s0      /run/netns/tmp

**Comment by lhh** [comment]
See:

https://bugzilla.redhat.com/show_bug.cgi?id=1687485#c4

Whatever is unconfined_service_t should be fixed. For now, we can merge this as-is, but there's a bug in either Octavia or the Amphora image generation.

**Comment by nmagnezi** [comment]
Lon,

As a followup to the [rhbz comment](https://bugzilla.redhat.com/show_bug.cgi?id=1687485#c4) you mentioned, the network namespace is [created on run time](https://github.com/openstack/octavia/blob/f935cab2085ce8628f0dac170f90f6662c90664e/octavia/amphorae/backends/agent/api_server/plug.py#L116) (not when we generate the image) by a Python agent we invoke named the Amphora agent.
 This agent is used to control the operating system network configuration (and for other things) from Octavia control plane.

**Comment by lhh** [comment]
Okay - we can look in to the various things we can fix up; the agent should have its own security label - which then the mount point would inherit.

**Pull request merged**
