### PR TITLE
Allow keepalived_t setattr for neutron_var_lib_t

### PR DESCRIPTION
**Pull request by tobias-urdin**
When upgrading to CentOS 8 2105 (8.4) things started to break again.

### CODE REVIEW

**Comment by tobias-urdin** [comment]
First one, keepalived_t needs setattr for PID files in neutron_var_lib_t

```
#============= keepalived_t ==============
allow keepalived_t neutron_var_lib_t:file setattr;
```

```
type=AVC msg=audit(1622799389.155:390): avc:  denied  { setattr } for  pid=4715 comm="keepalived" name="1171ec49-19e7-4b89-a97c-88d5e8732bf8.pid.keepalived" dev="dm-0" ino=237885 scontext=system_u:system_r:keepalived_t:s0 tcontext=system_u:object_r:neutron_var_lib_t:s0 tclass=file permissive=1

type=AVC msg=audit(1622799392.683:404): avc:  denied  { setattr } for  pid=4808 comm="keepalived" name="0a74a7c4-8735-4aea-8b16-0e46780c9a39.pid.keepalived" dev="dm-0" ino=237887 scontext=system_u:system_r:keepalived_t:s0 tcontext=system_u:object_r:neutron_var_lib_t:s0 tclass=file permissive=1

type=AVC msg=audit(1622799420.386:566): avc:  denied  { setattr } for  pid=5621 comm="keepalived" name="db8f00f6-b84f-4ec1-b96a-24b46200c26b.pid.keepalived" dev="dm-0" ino=232460 scontext=system_u:system_r:keepalived_t:s0 tcontext=system_u:object_r:neutron_var_lib_t:s0 tclass=file permissive=1
```

**Comment by tobias-urdin** [comment]
The other ones I'm not quite sure, but it seems related to the rootwrap daemon that is started with sudo.

```
type=AVC msg=audit(1622799052.400:3390): avc:  denied  { getpgid } for  pid=7501 comm="sudo" scontext=system_u:system_r:neutron_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=process permissive=1

type=AVC msg=audit(1622799052.671:3399): avc:  denied  { getpgid } for  pid=6651 comm="sudo" scontext=system_u:system_r:neutron_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=process permissive=1

type=AVC msg=audit(1622799054.977:3463): avc:  denied  { remove_name } for  pid=1 comm="systemd" name="rootwrap.sock" dev="dm-0" ino=134341250 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:neutron_tmp_t:s0 tclass=dir permissive=1

type=AVC msg=audit(1622799054.977:3463): avc:  denied  { unlink } for  pid=1 comm="systemd" name="rootwrap.sock" dev="dm-0" ino=134341250 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:neutron_tmp_t:s0 tclass=sock_file permissive=1

type=AVC msg=audit(1622799054.977:3464): avc:  denied  { rmdir } for  pid=1 comm="systemd" name="rootwrap-hud9qp6c" dev="dm-0" ino=134341249 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:neutron_tmp_t:s0 tclass=dir permissive=1
```

```

#============= init_t ==============
allow init_t neutron_tmp_t:dir { remove_name rmdir };
allow init_t neutron_tmp_t:sock_file unlink;

#============= neutron_t ==============
allow neutron_t init_t:process getpgid;
```

In neutron.conf
```
root_helper=sudo neutron-rootwrap /etc/neutron/rootwrap.conf
root_helper_daemon=sudo neutron-rootwrap-daemon /etc/neutron/rootwrap.conf
``

**Comment by tobias-urdin** [comment]
lsof on rootwrap process when running in permissive mode shows it's using /tmp

```
COMMAND    PID USER   FD   TYPE             DEVICE SIZE/OFF      NODE NAME
..snip..
neutron-r 6566 root    3u  unix 0xffff945a98760000      0t0    128727 /tmp/rootwrap-3dwhfe8u/rootwrap.sock type=STREAM
neutron-r 6566 root    5u  unix 0xffff9459b6658900      0t0    131870 /tmp/rootwrap-3dwhfe8u/rootwrap.sock type=STREAM
``

**Comment by tobias-urdin** [comment]
Can ignore all the sudo and systemd related ones, they are either 1) related to systemd trying to save you when issuing a reboot or 2) the sudo error is when neutron tries to spawn a rootwrap daemon but it is already running.

So only the keepalived change mentioned in the PR is valid it seems, I will validate with some more testing.

**Comment by tobias-urdin** [comment]
@jpichon If we could get a ticket in the bugtracker I can update the back, thanks!

**Comment by jpichon** [comment]
Hi Tobias, thank you for the detailed PR and careful analysis, appreciated as always. I was out for a few days but I opened https://bugzilla.redhat.com/show_bug.cgi?id=1969325 now for the tests. You're welcome to create these BZs yourself if you'd like, by the way! The tracker is open to everyone, and the project is "Community -> RDO" then "openstack-selinux" for the component. I'm the default assignee and normally get these in my inbox as well.

At first glance, this change looks fine and makes sense to me.

**Comment by tobias-urdin** [comment]
Ah, a shame that I've been bothering you about that then! I'll sign up for next time, thanks!

**Review by jpichon — APPROVED** [review]
Change looks good to me, thank you for the update! And no worries, sorry for not making it clearer earlier and slowing you down. I'll tag this after merging.

**Comment by jpichon** [comment]
Tagged as 0.8.27.

**Pull request merged**
