### PR TITLE
Revert "Sensu: Allow containers to connect to systemd sockets"

### PR DESCRIPTION
**Pull request by cjeanner**
This reverts commit 66e8a6f7313b5fbe9954396960e05f35f62c4e5c.

The added policy created a security risk where a compromised container
could stop services with a crafted DBus call.

### CODE REVIEW

**Comment by jpichon** [comment]
Let me know when the changes required elsewhere are done and we can merge this. I'm not sure about the status.

**Comment by cjeanner** [comment]
Hello @jpichon ! I just talked to Martin, we should be able to merge this one now :).

**Comment by jpichon** [comment]
I think we still need to pin openstack-selinux in RDO first for stable/stein to avoid breaking it/OSP15. As far as I can tell from the BZs, the fix wasn't backportable to Stein and wasn't recreated there.

**Comment by jpichon** [comment]
Proposed https://review.rdoproject.org/r/#/c/28755/ to pin Stein to known openstack-selinux that will work with sensu. We can merge this PR once the pinning is done.

**Pull request merged**
