### PR TITLE
Revert "Add boolean to optionally enable PBIS support for nova_t/neutron_t"

### PR DESCRIPTION
**Pull request by kajinamit**
This reverts commit 1b65945ea05a34e3de3aa92d994b9f6221fe3e0b.

Reason for revert:
The original issue was fixed in the PBIS package by [1].

[1] https://github.com/BeyondTrust/pbis-open/commit/b1ffc871065cb13fcdde0f60c522a80a658c607a

Conflicts:
	Makefile

### CODE REVIEW

**Comment by jpichon** [comment]
Thank you for the clean-up patch! Because #103 merged first, there is now a conflict in the Makefile. I also need a little bit of time to confirm something about versions in relation to this patch. I appreciate the pointer to the pbis-open repository and relevant commit, this is really helpful.

**Comment by kajinamit** [comment]
Thanks @jpichon . I've resolved the conflict and rebased the change on the current master.

**Comment by kajinamit** [comment]
We might want to deprecate os_pbis_client flag before we remove it, though I'm not too sure how much it would be useful assuming usage of pbis is not much common.

**Comment by jpichon** [comment]
Thank you for updating the PR! From what I understand, the open-source part of that project may be archived, but the main project still exists. I'm not sure if it was just renamed or what changed, but I do remember we had users who experienced some grief before we could get this patch in, so I want to gather what versions I can before merging. Thanks again for taking the time to propose those clean-ups, and for your patience!

**Review by jpichon — APPROVED** [review]
Thank you for the clean-up!

**Pull request merged**
